# Generated by Django 5.1.5 on 2025-02-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(upload_to='feeds/'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='profile_image',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
